version: '3.1'

services:

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./state/mongo/configdb:/data/configdb
      - ./state/mongo/db/:/data/db
    ports: 
      - 27017:27017

  
#  annotationtool:
#    build: ./backend
#    restart: always
#    depends_on:
#      - mongodb
#      - autoannotator

#    links:
#      - mongodb
#      - autoannotator
#    ports: 
#      - 3000:3000

#    volumes: 
#      - ./state/files:/files

#  autoannotator:
#    restart: always
#    build: ./autoannotator
#    volumes: 
#      - ./state/files:/files

